@startuml
scale 0.7
set separator none
package unibo.exiled
{
  package view{
    class GameView {
      + draw()
      + etc...()
    }
    
    class GameOverView {
      + display(): void
    }
    
    class GameVictoryView {
      + display(): void
    }
  }
  package controller {
    class GameController {
      + isOver(): boolean
      + isWon(): boolean
      + etc...()
    }
  }

}

GameView *-- "1" GameOverView 
GameView *-- "1" GameVictoryView 
GameView *-- "1" GameController
@enduml

