@startuml
scale 0.5
class ItemContainer {
    -ITEMS: Set<Item>
    +getItemByName(name: String): Optional<Item>
    +getAllItems(): Set<Item>
    +getRandomItemByType(type: ItemType): Optional<Item>
    +getRandomItem(): Optional<Item>
    -getRandomItemFromList(itemList: List<Item>): Optional<Item>
}

interface ItemFactory {
    +createHealingItem(name: String, description: String, healingAmount: double): HealingItem
    +createPowerUpItem(name: String, description: String, powerUpValue: double, boostedAttribute: AttributeIdentifier): PowerUpItem
    +createUnUsableItem(name: String, description: String): UnUsableItem
}

class ItemFactoryImpl {
}

class ItemNames {
    
}

ItemContainer --> Item
ItemContainer --> ItemNames
ItemContainer --> ItemFactory
ItemFactory --> Item
ItemFactoryImpl --|> ItemFactory
@enduml