@startuml
scale 0.4
interface Item {
    +getName()
    +getDescription()
    +getType()
}

enum ItemType {
    HEALTH
    POWERUP
    RESOURCE
}

class ItemBase {
}

class HealingItem {
}

interface UsableItem {
    +use(player: Player)
    +getAmount()
}

class PowerUpItem {
    +getBoostedAttribute()
}

interface Player {
    +useItem(item: UsableItem)
}

class UnUsableItem {
}

enum AttributeIdentifier{
}

Item <|-- ItemBase
Item--|> ItemType

HealingItem --|> ItemBase
PowerUpItem --|> ItemBase
PowerUpItem --|> AttributeIdentifier
UnUsableItem --|> ItemBase

UsableItem <|.. HealingItem
UsableItem <|.. PowerUpItem

Player --> UsableItem
@enduml