@startuml
scale 0.60
set separator none
package unibo.exiled.model.move
{
    enum MagicMove{
        {field} WATER_PISTOL(...)
        {field} THUNDERSTORM(...)
        {field} LEECHERS(...)
        {field} FIRE_WHIRL(...)
        {field} ...
        .. Fields of the enum ..
        - name : String
        - description : String
        - power : double
        - type : ElementalType
        __ Getters of the enum __
        + getName() : String
        + getDescription() : String
        + getPower() : double
        + getType() : ElementalType
    }
    interface MoveSet {
        getMagicMoves() : Set<MagicMove>
        changeMove(MagicMove oldMove,\n                     MagicMove newMove) : boolean
        addMagicMove(MagicMove) : void
    }
    class MoveSetImpl implements MoveSet{
        - magicMoves : Set<MagicMove>
        + getMagicMoves() : ...
        + changeMove(...) : boolean
        + addMagicMove(MagicMove) : void
    }
    package factory{
        interface MoveSetFactory {
            defaultNormalMoveSet() : MoveSet
            defaultFireMoveSet() : MoveSet
            defaultWaterMoveSet() : MoveSet
            ...()
            boltBossMoveSet() : MoveSet
            fireBossMoveSet() : MoveSet
            ...()
        }
        class MoveSetFactoryImpl implements MoveSetFactory {
            - fillMoveSet(final MagicMove... moves) : MoveSet
            + defaultNormalMoveSet() : MoveSet
            + defaultFireMoveSet() : MoveSet
            +...()
        }
    }
}
MoveSet <.. MoveSetFactory
MoveSet o- MagicMove
@enduml